### PR TITLE
Troposphere and recovery feature

### PR DESCRIPTION
**Pull request by MatthewVita**

### CODE REVIEW

**Comment by MatthewVita** [comment]
@jesdynf okay sir. This is all reviewed, smoke tested, tweaked slightly (requirements.txt and a few doc changes), and squashed. Please take a look and then once you're happy, I'm sure @danielehrlich will be kind enough to do some QA :)

**Review by jesdynf — APPROVED** [review]
Looks good!

**Comment by MatthewVita** [comment]
@danielehrlich okay sir, it's up to you :). Please do some testing on this and then merge it

**Comment by ghost** [comment]
I'll look at all this tomorrow, good stuff (before GoT of course).

Rain is pretty bad, but our apartment is second floor!!

**Comment by jesdynf** [comment]
Superceded by #66.

**Pull request closed without merging**
