### PR TITLE
Moving user-configurable variables to single file to be set as enviro…

### PR DESCRIPTION
**Pull request by bponath**
…nment variables.

### CODE REVIEW

**Comment by MatthewVita** [comment]
@bponath Very nice! High quality stuff.

Before merging, do you mind updating the bits of the guide that have the user update these values? This is the not-so-fun work, but it is important to hold the end user's hand through the guide...

**Comment by bponath** [comment]
@MatthewVita Thanks. Good catch. I updated the guide.

**Comment by MatthewVita** [comment]
Very nice! Thanks for that.

**Comment by MatthewVita** [comment]
Just marked the Asana task as complete. If you're up for it, this ticket is open for work: https://app.asana.com/0/346554951567668/372451402901715

**Pull request merged**
